services:
  mongodb:
    image: bitnami/mongodb:7.0
    ports:
      - "27017:27017"
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ADVERTISED_HOSTNAME: localhost
      ALLOW_EMPTY_PASSWORD: 'yes'